### ISSUE TITLE
Plugin Name

### ISSUE THREAD

**Issue by jonathandey** [jonathandey/oc-jd-dingoapi#2]
The Dingo API licence states:

> Neither the name of Dingo API nor the names of its
> contributors may be used to endorse or promote products derived from
> this software without specific prior written permission.

I have made contact with @jasonlewis on the larachat slack channel but haven't heard anything back as of yet. I may have to rename the plugin...

**Comment by jasonlewis** [comment]
This is an integration plugin for Dingo with October? Should be fine mate.

**Comment by jonathandey** [comment]
That's the plan! Thanks for getting back to me.
