### ISSUE TITLE
What does the request look like that it is possible to read parameter using Input::get('password')?

### ISSUE THREAD

**Issue by chrisiek** [jonathandey/oc-jd-dingoapi#5]
I can't imagine how to make a request to be able to use `Input::get('password')` exactly as you did in `routes.example.php`

Can you give an example of such a request, including parameters' names and their values?

**Comment by jonathandey** [comment]
Personally I have used `request()->get('password')`, but I believe this will give you the same result. As I'm not able to replicate the issue I do not believe this is an issue related to the Plugin. Please see the [Laravel docs (5.1)](laravel.com/docs/5.1) or [Dingo/API wiki](https://github.com/dingo/api/wiki/). This plugin is simply a wrapper for the Dingo/API.
