### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by nest-don** [jonathandey/oc-jd-dingoapi#7]
How do you install this please?  

do you use composer i.e.

composer require "jonathandey/oc-jd-dingoapi:*"

or do you manually copy this to the plugin folder?

i copied the folder manually to plugins/oc-jd-dingoapi but the plugin does not seem to be recognised.

**Comment by jonathandey** [comment]
To install the plugin you need to first create a folder within your plugins directory called "jd" (this is the author folder). The you need to clone this repository in to that folder `git clone https://github.com/jonathandey/oc-jd-dingoapi.git dingoapi`
You should then be up and running :)

**Comment by nest-don** [comment]
Thank you so much for an excellent project.  It saved me lots of time.

**Comment by jonathandey** [comment]
No problem! I can't take too much credit though, the heavy lifting is done by the [Dingo/Api](https://github.com/dingo/api) project.
