### ISSUE TITLE
October\Rain\Events\Dispatcher given error

### ISSUE THREAD

**Issue by AugmentBLU** [jonathandey/oc-jd-dingoapi#8]
I'm trying your plugin with OC 426 which uses Laravel 5.5 but I'm getting this error. I tried to tinker with it but not getting very far. Any ideas?

```
Type error: Argument 1 passed to Dingo\Api\Http\Response::setEventDispatcher() must be an instance of Illuminate\Events\Dispatcher, instance of October\Rain\Events\Dispatcher given, called in /home/vagrant/website/vendor/dingo/api/src/Provider/DingoServiceProvider.php on line 37

```

**Comment by jonathandey** [comment]
I will have to look in to this. It looks like October\Rain dispatcher now extends `Illuminate\Contracts\Events\Dispatcher` rather than `Illuminate\Events\Dispatcher`.

This may require an update from DingoApi. If they haven't done it already!

**Comment by jonathandey** [comment]
The class `Illuminate\Events\Dispatcher` still exists in Illuminate it just looks like OC have decided to write their own implementation rather than extend it.

While I look in to this, it might be worth asking them why they have chosen to do this.

**Comment by AugmentBLU** [comment]
Thanks for the reply.

I spoke with Spunky and Luke on Slack and they're making some changes to how OC extends Laravel to make it more compatible. I'm not sure if this will help this issue out but we will see.

I had to make 2 hardcoded changes to the dingo api to get it to work with OC.  Changed the Response and Middleware Request files. Not ideal but it helped.

`use October\Rain\Events\Dispatcher as EventDispatcher;`

**Comment by nest-don** [comment]
AugmentBLU,  what changes did you make to the Response and Middleware Request files?

**Comment by jaaparenas** [comment]
I have changed the same code in the file... dingo/api/src/Http/Response.php

**Comment by chrisvidal** [comment]
as for 10 of September 2018, the issue is still there and has to be hard coded patched.

**Comment by jonathandey** [comment]
This should now be resolved.
