### ISSUE TITLE
Class jd.dingoapi.auth does not exist in

### ISSUE THREAD

**Issue by chrisvidal** [jonathandey/oc-jd-dingoapi#9]
I updated the plugin.php with my own class auth class  and have this error
`Class jd.dingoapi.auth does not exist in oc-vodka/vendor/laravel/framework/src/Illuminate/Container/Container.php:752`

```php
$this->app->singleton('jd.dingoapi.auth', function() {
            return \Vodka\Api\Classes\AuthManager::instance();
        });
```

**Comment by jonathandey** [comment]
This should now be resolved. Thanks!
